FAMILY  = artix7
PART    = xc7a100tcsg324-1
BOARD   = nexys_a7_100
PROJECT = nexys_game
TOP_MODULE = nexys_top
TOP_VERILOG = nexys_top.v
ADDITIONAL_SOURCES = project.v
XDC     = nexys_a7.xdc
CHIPDB  = ./chipdb
SYNTH_OPTS = -nodsp

# Ruta al archivo de configuración del repo de herramientas
include ../../chip-invaders-main/xc7-demo-projects/openXC7.mk
